package info.masterfrog.labyrinth.enumeration;

public enum EntityHandle {
    // Common
    // N/A

    // Start Screen
    START_SCREEN__BACKGROUND,
    START_SCREEN__DEV_LOGO,
    START_SCREEN__TITLE_TEXT,
    START_SCREEN__START_TEXT,
    START_SCREEN__FOOTNOTE_TEXT,

    // Labyrinth
    LABYRINTH__CHARACTER,
    LABYRINTH_ROOM_1,
    LABYRINTH_ROOM_2,
    LABYRINTH_ROOM_3,
    LABYRINTH_ROOM_4,
    LABYRINTH_ROOM_5,
    LABYRINTH_ROOM_6,
    LABYRINTH_ROOM_7,
    LABYRINTH_ROOM_8,
    LABYRINTH_ROOM_9,
    LABYRINTH_ROOM_10,
    LABYRINTH_ROOM_11,
    LABYRINTH_ROOM_12,

    // Menu
    MENU__BACKGROUND,
    MENU__TITLE_TEXT,
    MENU__RESUME_OPTION_TEXT,
    ;
}
