package info.masterfrog.labyrinth.enumeration;

public enum ResourceHandle {
    // Common
    // N/A

    // Start Screen
    START_SCREEN__SPRITE__BACKGROUND,
    START_SCREEN__SPRITE__TITLE,
    START_SCREEN__SPRITE__DEV_LOGO,
    START_SCREEN__SPRITE__START_TEXT,
    START_SCREEN__SPRITE__FOOTNOTE_TEXT,
    START_SCREEN__IMAGE__BACKGROUND,
    START_SCREEN__IMAGE__TITLE,
    START_SCREEN__IMAGE__DEV_LOGO,
    START_SCREEN__IMAGE__START_TEXT,
    START_SCREEN__IMAGE__FOOTNOTE_TEXT,
    START_SCREEN__SOUND__INTRO_MUSIC,

    // Labyrinth
    LABYRINTH__SPRITE__CHARACTER,
    LABYRINTH__IMAGE__CHARACTER,
    LABYRINTH__SPRITE__ROOM_BACKGROUND_BASE,
    LABYRINTH__SPRITE__ROOM_BACKGROUND_1X1,
    LABYRINTH__SPRITE__ROOM_BACKGROUND_3X3,
    LABYRINTH__SPRITE__ROOM_BACKGROUND_5X5,
    LABYRINTH__SPRITE__ROOM_BACKGROUND_7X7,
    LABYRINTH__SPRITE__ROOM_BACKGROUND_9X9,
    LABYRINTH__SPRITE__ROOM_BACKGROUND_11X11,
    LABYRINTH__SPRITE__ROOM_BACKGROUND_13X13,
    LABYRINTH__SPRITE__ROOM_BACKGROUND_15X15,
    LABYRINTH__IMAGE__ROOM_BACKGROUND_BASE,
    LABYRINTH__IMAGE__ROOM_BACKGROUND_1X1,
    LABYRINTH__IMAGE__ROOM_BACKGROUND_3X3,
    LABYRINTH__IMAGE__ROOM_BACKGROUND_5X5,
    LABYRINTH__IMAGE__ROOM_BACKGROUND_7X7,
    LABYRINTH__IMAGE__ROOM_BACKGROUND_9X9,
    LABYRINTH__IMAGE__ROOM_BACKGROUND_11X11,
    LABYRINTH__IMAGE__ROOM_BACKGROUND_13X13,
    LABYRINTH__IMAGE__ROOM_BACKGROUND_15X15,

    // Menu
    MENU__BACKGROUND,
    MENU__TITLE_TEXT,
    MENU__RESUME_OPTION_TEXT,
    ;
}
